# Generated by Django 5.1.7 on 2025-03-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContainerCpuMetrics',
        ),
    ]
