version: "3"
services:
  minio1:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes" # Enable distributed mode
    command: server --console-address ":9001" /data
    volumes:
      - ./minio_storage1:/data
    ports:
      - "9000:9000" # MinIO API port
      - "9001:9001" # MinIO Console port
    networks:
      - minio_network
    restart: always

  minio2:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes" # Enable distributed mode
    command: server --console-address ":9001" /data
    volumes:
      - ./minio_storage2:/data
    ports:
      - "9020:9000" # MinIO API port for the second node
      - "9021:9001" # MinIO Console port for the second node
    networks:
      - minio_network
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Load custom Nginx configuration
    ports:
      - "80:80" # Nginx proxy for load balancing
    depends_on:
      - minio1
      - minio2
    networks:
      - minio_network

volumes:
  minio1-data:
  minio2-data:

networks:
  minio_network:
    driver: bridge
