version: "3"
services:
  minio1:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "adminpassword"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes" # Enable distributed mode
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - minio1-data:/data
    ports:
      - "9000:9000" # MinIO API port
      - "9001:9001" # MinIO Console port
    networks:
      - minio_network

  minio2:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "adminpassword"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes" # Enable distributed mode
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - minio2-data:/data
    ports:
      - "9002:9000" # MinIO API port for the second node
      - "9003:9001" # MinIO Console port for the second node
    networks:
      - minio_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Load custom Nginx configuration
    ports:
      - "80:80" # Nginx proxy for load balancing
    depends_on:
      - minio1
      - minio2
    networks:
      - minio_network

volumes:
  minio1-data:
  minio2-data:

networks:
  minio_network:
    driver: bridge
