# Generated by Django 5.1.7 on 2025-03-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filechunk',
            name='checksum',
        ),
    ]
