# Generated by Django 5.1.7 on 2025-03-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0002_filechunk_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechunk',
            name='node_name',
            field=models.CharField(default='default_node', max_length=255),
        ),
    ]
